apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: link
  annotations:
    kubernetes.io/ingress.class: kong
  tps: lnk
  usecase: link
username: link
credentials:
  - companyone-key-auth
